package view;

/**
 *
 * @author Daniel Casvill
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpSell = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpBuy = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jTextField22 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(850, 650));
        setPreferredSize(new java.awt.Dimension(850, 720));
        getContentPane().setLayout(null);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(850, 850));

        jpSell.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 28)); // NOI18N
        jLabel1.setText("SELL");
        jpSell.add(jLabel1);
        jLabel1.setBounds(350, 30, 110, 60);

        jTabbedPane1.addTab("SELL", jpSell);

        jpBuy.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 1, 28)); // NOI18N
        jLabel2.setText("BUY");
        jpBuy.add(jLabel2);
        jLabel2.setBounds(330, 60, 110, 60);

        jLabel10.setText("SUPPLIER:");
        jpBuy.add(jLabel10);
        jLabel10.setBounds(220, 170, 100, 16);

        jpBuy.add(jComboBox2);
        jComboBox2.setBounds(346, 160, 170, 26);

        jLabel11.setText("PRODUCT NAME:");
        jpBuy.add(jLabel11);
        jLabel11.setBounds(220, 220, 100, 16);

        jpBuy.add(jComboBox3);
        jComboBox3.setBounds(346, 210, 170, 26);

        jLabel12.setText("QUANTITY:");
        jpBuy.add(jLabel12);
        jLabel12.setBounds(220, 280, 90, 16);
        jpBuy.add(jSpinner1);
        jSpinner1.setBounds(350, 270, 80, 26);

        jButton16.setText("jButton16");
        jpBuy.add(jButton16);
        jButton16.setBounds(220, 370, 130, 27);

        jButton17.setText("jButton17");
        jpBuy.add(jButton17);
        jButton17.setBounds(410, 370, 130, 27);

        jTabbedPane1.addTab("BUY", jpBuy);

        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 1, 28)); // NOI18N
        jLabel4.setText("PRODUCTS");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(300, 10, 260, 80);

        jLabel18.setText("ID:");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(170, 90, 120, 16);

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField17);
        jTextField17.setBounds(360, 80, 320, 26);
        jPanel3.add(jTextField18);
        jTextField18.setBounds(360, 130, 320, 26);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(60, 220, 710, 320);

        jLabel20.setText("SUPPLIER:");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(170, 190, 120, 16);

        jLabel21.setText("PRODUCT NAME:");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(170, 140, 120, 16);
        jPanel3.add(jTextField21);
        jTextField21.setBounds(700, 560, 120, 26);

        jButton11.setText("DELETE");
        jPanel3.add(jButton11);
        jButton11.setBounds(700, 600, 120, 27);
        jPanel3.add(jTextField22);
        jTextField22.setBounds(540, 560, 120, 26);

        jButton12.setText("SEARCH");
        jPanel3.add(jButton12);
        jButton12.setBounds(540, 600, 120, 27);

        jButton13.setText("LIST ALL");
        jPanel3.add(jButton13);
        jButton13.setBounds(380, 600, 120, 27);

        jButton14.setText("UPDATE");
        jPanel3.add(jButton14);
        jButton14.setBounds(220, 600, 120, 27);

        jButton15.setText("SAVE");
        jPanel3.add(jButton15);
        jButton15.setBounds(50, 600, 120, 27);

        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(360, 180, 320, 26);

        jTabbedPane1.addTab("PRODUCTS", jPanel3);

        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Yu Gothic Light", 1, 28)); // NOI18N
        jLabel5.setText("CUSTOMERS");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(290, 10, 200, 80);

        jLabel6.setText("ID:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(170, 90, 120, 16);

        jLabel7.setText("NAME:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(170, 140, 120, 16);

        jLabel8.setText("SURNAMES:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(170, 190, 120, 16);

        jLabel9.setText("PHONE NUMBER:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(170, 240, 120, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1);
        jTextField1.setBounds(360, 80, 320, 26);
        jPanel4.add(jTextField2);
        jTextField2.setBounds(360, 130, 320, 26);
        jPanel4.add(jTextField3);
        jTextField3.setBounds(360, 180, 320, 26);
        jPanel4.add(jTextField4);
        jTextField4.setBounds(360, 230, 320, 26);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(60, 290, 710, 250);

        jButton1.setText("SAVE");
        jPanel4.add(jButton1);
        jButton1.setBounds(50, 600, 120, 27);

        jButton2.setText("UPDATE");
        jPanel4.add(jButton2);
        jButton2.setBounds(220, 600, 120, 27);

        jButton3.setText("LIST ALL");
        jPanel4.add(jButton3);
        jButton3.setBounds(380, 600, 120, 27);

        jButton4.setText("SEARCH");
        jPanel4.add(jButton4);
        jButton4.setBounds(540, 600, 120, 27);

        jButton5.setText("DELETE");
        jPanel4.add(jButton5);
        jButton5.setBounds(700, 600, 120, 27);
        jPanel4.add(jTextField5);
        jTextField5.setBounds(540, 560, 120, 26);
        jPanel4.add(jTextField6);
        jTextField6.setBounds(700, 560, 120, 26);

        jTabbedPane1.addTab("CUSTOMERS", jPanel4);

        jPanel5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Yu Gothic Light", 1, 28)); // NOI18N
        jLabel3.setText("SUPPLIERS");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(290, 10, 260, 80);

        jLabel14.setText("ID:");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(170, 90, 120, 16);

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField11);
        jTextField11.setBounds(360, 80, 320, 26);
        jPanel5.add(jTextField12);
        jTextField12.setBounds(360, 130, 320, 26);
        jPanel5.add(jTextField13);
        jTextField13.setBounds(360, 180, 320, 26);
        jPanel5.add(jTextField14);
        jTextField14.setBounds(360, 230, 320, 26);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(60, 290, 710, 250);

        jLabel15.setText("PHONE NUMBER:");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(170, 240, 120, 16);

        jLabel16.setText("SURNAMES:");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(170, 190, 120, 16);

        jLabel17.setText("NAME:");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(170, 140, 120, 16);
        jPanel5.add(jTextField15);
        jTextField15.setBounds(700, 560, 120, 26);

        jButton6.setText("DELETE");
        jPanel5.add(jButton6);
        jButton6.setBounds(700, 600, 120, 27);
        jPanel5.add(jTextField16);
        jTextField16.setBounds(540, 560, 120, 26);

        jButton7.setText("SEARCH");
        jPanel5.add(jButton7);
        jButton7.setBounds(540, 600, 120, 27);

        jButton8.setText("LIST ALL");
        jPanel5.add(jButton8);
        jButton8.setBounds(380, 600, 120, 27);

        jButton9.setText("UPDATE");
        jPanel5.add(jButton9);
        jButton9.setBounds(220, 600, 120, 27);

        jButton10.setText("SAVE");
        jPanel5.add(jButton10);
        jButton10.setBounds(50, 600, 120, 27);

        jTabbedPane1.addTab("SUPPLIERS", jPanel5);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 850, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel jpBuy;
    private javax.swing.JPanel jpSell;
    // End of variables declaration//GEN-END:variables
}
